### PR TITLE
remove background and add letters to ggchessboard

### PR DESCRIPTION
**Pull request by oganm**

### CODE REVIEW

**Comment by jbkunst** [comment]
Hi @oganm 

Can you send me a image with the change please? 😅

**Comment by oganm** [comment]
Yup. The only difference is the removal of the grey background leftover from `theme_gray` and replaces the letters for the x axis

```r
pgn = system.file("extdata/pgn/kasparov_vs_topalov.pgn", package = "rchess")
pgn = readLines(pgn, warn = FALSE)
pgn <- paste(pgn, collapse = "\n")
board = rchess::Chess$new()
board$load_pgn(pgn)
ggchessboard(board$fen())
```
image

**Comment by jbkunst** [comment]
Perfect! Do you think it is a good idea remove the ticks to have a cleaner chart?

image

(from http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels)

Please do not forget to add yourself to the list of contributors :). See https://github.com/jbkunst/rchess/blob/master/DESCRIPTION#L10

**Comment by oganm** [comment]
yep. was wondering if I would have to bring the text closer when the ticks are gone but I guess it looks fine?

image

**Comment by jbkunst** [comment]
Maybe enlarge the letters a little bit solves that problem too.

Anyway if you consider this is fine I will merge ;). Thanks again :D.

**Comment by oganm** [comment]
Added it as the `labelsize` argument and enlarged it a little. Not sure about that name

image

**Comment by oganm** [comment]
I didn't do a `devtools::document` because your line endings seem to change creating a mess.

**Comment by jbkunst** [comment]
LGTM, if you are agree I'll merge and document the package later.

**Comment by oganm** [comment]
yay!

**Comment by jbkunst** [comment]
Thanks 😄

**Pull request merged**
